import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { Separator } from "@/components/ui/separator";
import { ThemeProvider } from "@/hooks/theme-provider";
import { ModeToggler } from "@/components/mode-toggler";
import { Toaster } from "react-hot-toast";
import { Providers } from "@/components/providers";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";
import LoginSignupFrame from "@/components/ui/login-signup-frame";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "zerotier-gui",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster position="top-center" />
        <Providers>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <SidebarProvider>
              {session?.user && <AppSidebar />}
              <SidebarInset>
                <header className="border-b p-4 text-lg font-medium flex h-16 transition-[hight,width]">
                  {session?.user && (
                    <>
                      <SidebarTrigger className="mr-4" />
                      <Separator orientation="vertical" />
                    </>
                  )}

                  <div className="ml-4 mr-auto">zerotier-gui</div>

                  <LoginSignupFrame session={session} />

                  <ModeToggler />
                </header>
                <div className="m-5">{children}</div>
              </SidebarInset>
            </SidebarProvider>
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
